### ISSUE TITLE
Start Headers on Different Row

### ISSUE THREAD

**Issue by ghost** [m0rtadelo/to-excel#17]
So in my case, I have something like this:

90 Day Parts Purchase History
2021-03-25 to 2021-06-23
Customer Number: 1097800
Customer Name: CUSTOMER NAME

itemNumber | Item Number | 30 Day Supply 
------------ | ------------- | -------------
2838992 | A01 | 0
89472728 | A02 | 2

Where the top 4 lines need to be in the first column and THEN the headers start (so they would start on row 6 in this case.
Is this possible with this library or do I need to search for a different one? :(

**Comment by m0rtadelo** [comment]
sorry. This library can't do that.
