### ISSUE TITLE
Bug with setReplace

### ISSUE THREAD

**Issue by JaoodxD** [m0rtadelo/to-excel#21]
I have an array with some statistical information, that has field 'Skip' with boolean value true\false.

To make table a bit more reprentative I would like to replace boolean values with it's natural "names" so I have to put true and false into setRepace function (as we can see in the listing below).
But somehow the replacement works fine only for true.

let headers = [{
            label: "ID заказа",
            field: "ID"
        },
        {
            label: "Номер конструкции",
            field: "POS"
        },
        {
            label: "Дата",
            field: "ACTDATE"
        },{
            label: "Фиктивные элементы",
            field: "Skip"
        },
    ];
    toExcel.setReplace(true, "Есть");
    toExcel.setReplace(false, "Нет");
    let content = toExcel.exportXLS(headers, result, 'fictive-element-statistics');
    fs.writeFileSync("fictive-element-statistics.xls", content);

**Comment by m0rtadelo** [comment]
Working on fix

**Comment by m0rtadelo** [comment]
Fixed in version 2.2.5
